export const translate = {
  name: "Имя",
  save: "Сохранить",
  SaveAs: "Сохранить как",
  back: "Назад",
  loading: "Загрузка...",
  resetOperations: "Сбросить/удалить все операции",
  changesLoseConfirmation: "Все изменения будут потеряны",
  changesLoseConfirmationHint: "Вы уверены, что хотите продолжить?",
  cancel: "Отмена",
  continue: "Продолжить",
  undoTitle: "Отменить последнюю операцию",
  redoTitle: "Повторить последнюю операцию",
  showImageTitle: "Показать исходное изображение",
  zoomInTitle: "Увеличить",
  zoomOutTitle: "Уменьшить масштаб",
  toggleZoomMenuTitle: "Переключить масштабирование меню",
  adjustTab: "Настроить",
  finetuneTab: "Настроить",
  filtersTab: "Фильтры",
  watermarkTab: "Водяной знак",
  annotateTab: "Рисовать",
  resize: "Изменять размер",
  resizeTab: "Обрезать",
  invalidImageError: "Предоставлено неверное изображение.",
  uploadImageError: "Ошибка при загрузке изображения.",
  areNotImages: "являются не изображения",
  isNotImage: "не изображение",
  toBeUploaded: "подлежит загрузке",
  cropTool: "Обрезка",
  original: "Оригинал",
  custom: "Пользовательский",
  square: "Квадрат",
  landscape: "Пейзаж",
  portrait: "Портрет",
  ellipse: "Эллипс",
  classicTv: "Классическое телевидение",
  cinemascope: "Синемаскоп",
  arrowTool: "Стрелка",
  blurTool: "Размытие",
  brightnessTool: "Яркость",
  contrastTool: "Контраст",
  ellipseTool: "Эллипс",
  unFlipX: "Не переворачивать X",
  flipX: "Переворачивать X",
  unFlipY: "Не переворачивать Y",
  flipY: "Переворачивать Y",
  hsvTool: "HSV",
  hue: "Оттенок",
  saturation: "Насыщенность",
  value: "Значение",
  imageTool: "Изображение",
  importing: "Импорт...",
  addImage: "+ Добавить изображение",
  uploadImage: "Загрузить изображение",
  fromGallery: "Из галереи",
  lineTool: "Линия",
  penTool: "Ручка",
  polygonTool: "Полигон",
  sides: "Стороны",
  rectangleTool: "Прямоугольник",
  cornerRadius: "Радиус угла",
  resizeWidthTitle: "Ширина в пикселях",
  resizeHeightTitle: "Высота в пикселях",
  toggleRatioLockTitle: "Переключение блокировки соотношения",
  reset: "Сброс",
  resetSize: "Возврат к исходному размеру изображения",
  rotateTool: "Поворот",
  textTool: "Текст",
  textSpacings: "Текстовые интервалы",
  textAlignment: "Выравнивание текста",
  fontFamily: "Семейство шрифтов",
  size: "Размер",
  letterSpacing: "Межбуквенный интервал",
  lineHeight: "Высота строки",
  warmthTool: "Тепло",
  addWatermark: "+ Добавить водяной знак",
  addWatermarkTitle: "Выбрать водяной знак тип",
  uploadWatermark: "Загрузить водяной знак",
  addWatermarkAsText: "Добавить как текст",
  padding: "Заполнение",
  shadow: "Тень",
  horizontal: "Горизонтальный",
  vertical: "Вертикальный",
  blur: "Размытие",
  opacity: "Непрозрачность",
  position: "Позиция",
  stroke: "Stroke",
  saveAsModalLabel: "Сохранить изображение как",
  extension: "Расширение",
  nameIsRequired: "Имя обязательно.",
  quality: "Качество",
  imageDimensionsHoverTitle:
    "Размер сохраненного изображения (ширина x высота)",
  cropSizeLowerThanResizedWarning:
    "Обратите внимание, выбранная область обрезки меньше примененного размера, что может привести к снижению качества",
  actualSize: "Фактический размер (100%)",
  fitSize: "Подходящий размер",
  addImageTitle: "Выберите изображение для добавления...",
};
